local MF = LibStub("AceAddon-3.0"):GetAddon("MacroForge")
local UI, E = MF:GetModule("UI"), MF:GetModule("Editor")
local errors = {}
local prev = geterrorhandler()
seterrorhandler(function(e) table.insert(errors, tostring(e)); return prev(e) end)
local function step(name, fn)
  local ok, err = xpcall(fn, function(e) return tostring(e) .. " | " .. debugstack(2, 3, 0) end)
  out(name, ok and "ok" or ("FAIL " .. err))
end
step("show", function() UI:Show() end)
step("home", function() UI:ShowDetail("home", "home") end)
step("audit", function() UI:ShowDetail("audit", "all") end)
step("templates", function() MF:GetModule("Templates"):OpenBrowser() end)
step("news", function() UI:ShowNews() end)
step("share import", function() MF:GetModule("Share"):OpenImport() end)
step("dupes", function() MF:GetModule("DuplicateDetector"):OpenBrowser() end)
step("back", function() UI:ClosePage(); UI:ClosePage(); UI:CloseAllPages() end)
local macro = MF:GetModule("Profiles"):ReadMacros("character")[1] or MF:GetModule("Profiles"):ReadMacros("account")[1]
out("macro", macro and macro.name)
step("open macro", function() E:OpenNew(true, true) end)
if macro then step("open existing", function() E:Open(macro, true) end) end
step("drawer spells", function() MF:GetModule("CommandPalette"):Toggle("spells") end)
step("drawer commands", function() MF:GetModule("CommandPalette"):Toggle("commands") end)
step("drawer builder", function() MF:GetModule("Builder"):Toggle() end)
step("drawer icons", function() MF:GetModule("IconPicker"):Toggle(function() end) end)
step("insert text", function() E:InsertText("x") end)
step("load content", function() E:LoadContent("T", "/cast x", 134400) end)
step("shorten", function() E:Shorten() end)
step("pick spell", function() MF:GetModule("CommandPalette"):InsertToEditor("Assommer") end)
step("close drawer", function() E:CloseDrawer() end)
step("export", function() E:OpenExport() end)
if macro then step("history", function() MF:GetModule("History"):OpenBrowser(macro) end) end
step("sets tab", function() UI:SetTab("sets") end)
step("trash tab", function() UI:SetTab("trash") end)
step("macros tab", function() UI:SetTab("macros") end)
step("test live", function() E:RunTest(); E:StopTest() end)
C_Timer.After(1.5, function() end)
out("errors", #errors)
for _, e in ipairs(errors) do out("E", e) end
